# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 64010a2f2080624a699b9bcd96b2beaa056a5479ce7ee5a80f5bbbe2eee30148814464827a48128e352b7fccaf053aac9712b6cc80ce3880c2c69f93dc5d2e40

test:
  secret_key_base: da8f92c0d18ae28c7bb7b8ba72d63acf184ba6d23331a5887e4ae0cfc415bcc49fa42d95e4107fdc6697d614a2d390b9fa12d12f3ae72edd8e065ab7eff6db3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
